import './globals.css'
import { Inter } from 'next/font/google'

const links = [{
  label: 'Home',
  route: '/'
}, {
  label: 'team',
  route: '/team'
}, {
  label: 'naves',
  route: '/'
}]

const inter = In  ter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
